# Generated by Django 5.0 on 2023-12-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_event_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='flatno',
            field=models.PositiveBigIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='signup',
            name='members',
            field=models.PositiveBigIntegerField(default=100),
        ),
    ]
