# Generated by Django 5.0 on 2023-12-28 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 28, 10, 19, 27, 323610, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 10, 19, 27, 323610, tzinfo=datetime.timezone.utc)),
        ),
    ]
